### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by anthony-cervantes** [mcueto/djangorestframework-auth0_sample#4]
Getting the following error when trying to follow the example:

```
Internal Server Error: /api/todos/
Traceback (most recent call last):
  File "/Users/anthony.cervantes/.virtualenvs/djangorestframework-auth0_sample/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/anthony.cervantes/.virtualenvs/djangorestframework-auth0_sample/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/anthony.cervantes/.virtualenvs/djangorestframework-auth0_sample/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/anthony.cervantes/.virtualenvs/djangorestframework-auth0_sample/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/anthony.cervantes/.virtualenvs/djangorestframework-auth0_sample/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/anthony.cervantes/.virtualenvs/djangorestframework-auth0_sample/lib/python2.7/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/anthony.cervantes/.virtualenvs/djangorestframework-auth0_sample/lib/python2.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/anthony.cervantes/.virtualenvs/djangorestframework-auth0_sample/lib/python2.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/anthony.cervantes/.virtualenvs/djangorestframework-auth0_sample/lib/python2.7/site-packages/rest_framework/views.py", line 471, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/anthony.cervantes/.virtualenvs/djangorestframework-auth0_sample/lib/python2.7/site-packages/rest_framework/views.py", line 388, in initial
    self.perform_authentication(request)
  File "/Users/anthony.cervantes/.virtualenvs/djangorestframework-auth0_sample/lib/python2.7/site-packages/rest_framework/views.py", line 314, in perform_authentication
    request.user
  File "/Users/anthony.cervantes/.virtualenvs/djangorestframework-auth0_sample/lib/python2.7/site-packages/rest_framework/request.py", line 222, in user
    self._authenticate()
  File "/Users/anthony.cervantes/.virtualenvs/djangorestframework-auth0_sample/lib/python2.7/site-packages/rest_framework/request.py", line 375, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/Users/anthony.cervantes/.virtualenvs/djangorestframework-auth0_sample/lib/python2.7/site-packages/rest_framework_auth0/authentication.py", line 45, in authenticate
    jwt_api_settings.JWT_ALGORITHM = client['AUTH0_ALGORITHM']
KeyError: 'AUTH0_ALGORITHM'
```

**Comment by mcueto** [comment]
Hi Anthony! i will check it tonight!

Thanks for the heads-up!

**Comment by mcueto** [comment]
@anthony-cervantes can you test it again? i just pushed the fix so now it would work

**Comment by anthony-cervantes** [comment]
👍 that worked, thanks!
